name: Build

on:
  push:
    branches: [ main ]
    paths: '**.swift'
  pull_request:
    branches: [ main ]
    paths: '**.swift'

jobs:
  build:

    runs-on: macos-11

    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: swift build -v
